# Generated by Django 3.1.7 on 2021-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210227_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='bg_pics/default.jpg', upload_to='bg_pics'),
        ),
    ]
